### ISSUE TITLE
Check that all the current tests run properly

### ISSUE THREAD

**Issue by alexlittle** [DigitalCampus/oppia-mobile-android#773]
With the new welcome screen I'm not sure if the tests all pass still, so these tests should be updated to reflect the current interface

**Comment by alexlittle** [comment]
I tried to run the tests on the v6.7.0 branch (new gradle etc) and get the following message:
`error: package android.test.mock does not exist`

**Comment by jbc25** [comment]
There were some issues with test libraries in new gradle version. I've already fixed them and created a pull request

**Comment by alexlittle** [comment]
When trying to run the tests on branch v6.8.0 (with the issue-773 branch merged in), I'm still having a problem running the tests:
`java.lang.Throwable: Unable to determine gradle tasks to execute
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:137)
	at com.android.tools.idea.gradle.run.DefaultGradleBuilder.build(DefaultGradleBuilder.java:42)
	at com.android.tools.idea.gradle.run.MakeBeforeRunTaskProvider.doExecuteTask(MakeBeforeRunTaskProvider.java:360)
	at com.android.tools.idea.gradle.run.MakeBeforeRunTaskProvider.executeTask(MakeBeforeRunTaskProvider.java:268)
	at com.android.tools.idea.gradle.run.MakeBeforeRunTaskProvider.executeTask(MakeBeforeRunTaskProvider.java:122)
	at com.intellij.execution.impl.ExecutionManagerImpl.lambda$compileAndRun$0(ExecutionManagerImpl.java:317)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by jbc25** [comment]
All tests are passing now
Remember to set a valid username and password in the test called: changeActivityWhenTheCredentialsAreCorrect

**Comment by alexlittle** [comment]
Thanks @jbc25  - could you also add something to the docs about setting the username/password?
